#!/usr/bin/env python3

# Copyright LLM.build Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# from .artifact import ArtifactStoreType, ArtifactType
# from .resources import ResourceSpec, ResourceTypefrom abc import ABC, abstractmethod
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Self, Union

from gbserver.storage import singleton_storage
from gbserver.storage.stored_build import StoredBuild
from gbserver.types.constants import (
    DEFAULT_GH_API_ENDPOINT,
    DEFAULT_ROOT_WORKSPACE_DIR,
    GBSERVER_GITHUB_TOKEN,
)
from gbserver.utils.filesystem import create_temp_subdir
from gbserver.utils.logger import get_logger

logger = get_logger(__name__)


class AbstractBuildRunner(ABC):
    """
    Common set of methods and defined behavior to run and monitor events after starting a StoredBuild.
    An instance of this is responsible for a single StoredBuild and for each build:
        1) Events generated by the build are captured and recorded in admin storage.
        2) Updating status of the build in the the PR associated with the StoredBuild, if any.

    Args:
        ABC (_type_): _description_
    """

    ### Constructor parameters ##################################
    # The build to be run
    stored_build: StoredBuild

    # The git token to use to update the PR of the build, if any.
    gh_token: str = GBSERVER_GITHUB_TOKEN

    # Looping interval for worker function
    monitoring_interval: int

    # Git api endpoint to register messages in the PR
    gh_api_endpoint: str

    # Workspace directory for running builds
    workspace_dir: Path

    # Lakehouse storage
    storage: singleton_storage.SingletonAdminStorage

    dry_run: bool = False

    def __init__(
        self: Self,
        build: StoredBuild,
        gh_token: str = GBSERVER_GITHUB_TOKEN,
        workspace_dir: Union[str, Path] = DEFAULT_ROOT_WORKSPACE_DIR,
        monitoring_interval: int = 5,
        gh_api_endpoint: str = DEFAULT_GH_API_ENDPOINT,
        dry_run: bool = False,
    ) -> None:
        if build is None:
            raise ValueError("build must be specified")
        self.dry_run = dry_run
        self.stored_build = build
        self.gh_token = gh_token
        self.monitoring_interval = monitoring_interval
        self.gh_api_endpoint = gh_api_endpoint

        if not isinstance(workspace_dir, str) and not isinstance(workspace_dir, Path):
            raise ValueError("workspace_dir must be a str or Path")
        workspace_dir = create_temp_subdir(workspace_dir)
        self.workspace_dir = workspace_dir.resolve()
        logger.debug("Will run build out of: %s", self.workspace_dir)

        # Kept as a convenience in case runners want to store the builds
        self.storage = singleton_storage.get_admin_storage()

    @abstractmethod
    def stop(self: Self) -> None:
        """
        Stop the build that was started using start_and_wait().
        Upon returning, this must also cause the call to start_and_wait() to return soon.
        This may return without waiting (i.e. immediately).
        """
        raise ValueError("Sub-class must implement this method")

    @abstractmethod
    def start_and_wait(self: Self) -> None:
        """
        Run the build that was provided to the initializer.
        Returns after the build has completed/failed/cancelled or stop() has been called from another thread.
        If the build is not finished and stop() has been called, then the build should be cancelled and marked in storage as CANCELLED.
        Upon completion self.workspace_dir should be removed.
        Upon completiong the build status is one of SUCCESS, FAILED or CANCELLED.
        raise ValueError("Sub-class must implement this method")
        """
