[supervisord]
nodaemon=true
user=root

[program:autotune-server]
command=python server.py
directory=/app/api
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/1
stderr_logfile_maxbytes=0
autostart=true
autorestart=true

[program:autotune-bridge]
command=python server.py
directory=/app/api-bridge
environment=API_BRIDGE_SERVER_PORT="8001"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/1
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
