name: bash-test
type: Bash
config: {}
assetstores:
  - store_uri: space://assetstores/hf/
    load:
      - mode: default
  - store_uri: space://assetstores/local/
    load:
      - mode: default
    push:
      - mode: default
