name: slurm-local
type: Skypilot
config:
  default_cloud: slurm
  idle_minutes_to_autostop: 0
assetstores:
  - store_uri: space://assetstores/hf/
    load:
      - mode: default
  - store_uri: space://assetstores/local/
    load:
      - mode: default
    push:
      - mode: default
