kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.route.name }}
  labels:
    {{- include "gb-ui.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/server-timeout: 600s
    haproxy.router.openshift.io/timeout: 600s  
spec:
  path: /
  host: {{ .Values.route.name }}.{{ .Values.route.namespace }}.vpc-int.res.ibm.com
  to:
    kind: Service
    name: {{ .Release.Name }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
