"""Structural unit tests for the `autotune` step asset (bash + docker copies)."""

import base64
import importlib.util
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

from gbserver.utils.template import fill_template

REPO_ROOT = Path(__file__).resolve().parents[4]
BASH_STEP = REPO_ROOT / "configurations/assets/environments/bash/steps/autotune"
DOCKER_STEP = REPO_ROOT / "configurations/assets/environments/docker/steps/autotune"
RUN_PY = BASH_STEP / "bash_scripts/autotune/run.py"
COMMAND_SH = BASH_STEP / "bash_scripts/autotune/command.sh"
SAMPLES = REPO_ROOT / "samples/autotune"
# Development source (steps/) vs. released assets (configurations/). Per
# steps/README.md, all new steps are authored under steps/ and the configurations/
# copy is generated by `make publish-step` -- so the source is the thing to edit.
BASH_SRC = REPO_ROOT / "steps/autotune/bash"
DOCKER_SRC = REPO_ROOT / "steps/autotune/docker"

SAMPLE_AUTOTUNE_CONFIG = {
    "training_config": {"tuning_algorithm": {"default": "lora"}},
    "tuners_config": {"lora": {"title": "LoRA"}},
}


def _load_run_module():
    spec = importlib.util.spec_from_file_location("autotune_run", RUN_PY)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _base_env(tmp_path):
    ds = tmp_path / "ds"
    ds.mkdir()
    (ds / "finance_train.jsonl").write_text("{}\n")
    (ds / "finance_validation.jsonl").write_text("{}\n")
    cfg = tmp_path / "autotune_config.yaml"
    cfg.write_text("training_config:\n  tuning_algorithm:\n    default: lora\n")
    out = tmp_path / "out"
    out.mkdir()
    return {
        "LLMB_BASH_INPUT_MODEL": "/models/granite",
        "LLMB_BASH_INPUT_DATASET_FILES": str(ds),
        "AUTOTUNE_CONFIG_FILE": str(cfg),
        "LLMB_BASH_OUTPUT_DIR": str(out),
        "JOB_ID": "job-123",
    }


class TestRunPyDriver:
    def test_build_argv_core_flags(self, tmp_path):
        mod = _load_run_module()
        argv = mod.build_argv(_base_env(tmp_path))
        assert argv[0] == "main.py"
        assert "--model_name_or_path" in argv
        assert argv[argv.index("--model_name_or_path") + 1] == "/models/granite"
        assert "--output_dir" in argv
        assert "--job_id" in argv and argv[argv.index("--job_id") + 1] == "job-123"
        # train/validation resolved by glob
        assert any(a.endswith("finance_train.jsonl") for a in argv)
        assert any(a.endswith("finance_validation.jsonl") for a in argv)

    def test_algo_default_read_from_config(self, tmp_path):
        mod = _load_run_module()
        argv = mod.build_argv(_base_env(tmp_path))
        assert argv[argv.index("--tuning_algo") + 1] == "lora"

    def test_bool_flags_added_when_true(self, tmp_path):
        mod = _load_run_module()
        env = _base_env(tmp_path)
        env.update({"NO_AUTOTUNE": "true", "CLEANUP": "1", "SAVE_HISTORY": "yes"})
        argv = mod.build_argv(env)
        assert (
            "--no_autotune" in argv and "--cleanup" in argv and "--save_history" in argv
        )

    def test_missing_required_input_exits(self, tmp_path):
        mod = _load_run_module()
        env = _base_env(tmp_path)
        del env["LLMB_BASH_INPUT_MODEL"]
        with pytest.raises(SystemExit):
            mod.build_argv(env)

    def test_artifact_marker_format_and_column0(self):
        mod = _load_run_module()
        marker = mod.artifact_marker("/abs/out")
        assert marker == "GB_ARTIFACT_ID:custom GB_ARTIFACT_PATH:/abs/out"

    def test_marker_starts_at_column_zero_after_a_partial_line(
        self, tmp_path, capsys, monkeypatch
    ):
        """Regression: the bash monitor's artifact regex is ^-anchored, and main.py
        (ray/tqdm) can leave a line unterminated. Without a leading newline the
        marker is appended to that line, never matches, and the output is silently
        lost -- skip_finding_output_artifacts removes the fallback scan.
        """
        mod = _load_run_module()
        env = _base_env(tmp_path)
        fm_tune = tmp_path / "fm-tune"
        fm_tune.mkdir()
        env["FM_TUNE_ROOT"] = str(fm_tune)

        def fake_run(argv, cwd=None):
            sys.stdout.write("Trial 3/8 [====>    ] 50%")  # no trailing newline

            class _P:
                returncode = 0

            return _P()

        monkeypatch.setattr(mod.os, "environ", env)
        monkeypatch.setattr(mod.subprocess, "run", fake_run)
        mod.main()

        lines = capsys.readouterr().out.splitlines()
        assert any(
            line.startswith("GB_ARTIFACT_ID:") for line in lines
        ), f"marker not at column 0; got {lines!r}"

    def test_no_marker_and_exit_code_propagated_on_failure(
        self, tmp_path, capsys, monkeypatch
    ):
        mod = _load_run_module()
        env = _base_env(tmp_path)
        fm_tune = tmp_path / "fm-tune"
        fm_tune.mkdir()
        env["FM_TUNE_ROOT"] = str(fm_tune)

        def fake_run(argv, cwd=None):
            class _P:
                returncode = 7

            return _P()

        monkeypatch.setattr(mod.os, "environ", env)
        monkeypatch.setattr(mod.subprocess, "run", fake_run)
        with pytest.raises(SystemExit) as exc:
            mod.main()
        assert exc.value.code == 7
        assert "GB_ARTIFACT_ID:" not in capsys.readouterr().out

    def test_ambiguous_split_glob_exits(self, tmp_path):
        """Two matching splits must fail loudly, not silently pick the first."""
        mod = _load_run_module()
        env = _base_env(tmp_path)
        Path(env["LLMB_BASH_INPUT_DATASET_FILES"], "legal_train.jsonl").write_text(
            "{}\n"
        )
        with pytest.raises(SystemExit) as exc:
            mod.build_argv(env)
        assert "ambiguous" in str(exc.value)

    def test_nonexistent_split_override_exits(self, tmp_path):
        mod = _load_run_module()
        env = _base_env(tmp_path)
        env["TRAIN_FILE"] = "does_not_exist.jsonl"
        with pytest.raises(SystemExit) as exc:
            mod.build_argv(env)
        assert "does not exist" in str(exc.value)

    def test_malformed_config_warns_instead_of_silently_defaulting(
        self, tmp_path, capsys
    ):
        mod = _load_run_module()
        env = _base_env(tmp_path)
        Path(env["AUTOTUNE_CONFIG_FILE"]).write_text("training_config: [unclosed\n")
        argv = mod.build_argv(env)
        assert argv[argv.index("--tuning_algo") + 1] == "lora"  # still defaults
        assert "autotune:" in capsys.readouterr().err  # but says so

    def test_backend_empty_falls_back_to_torch(self, tmp_path):
        """`--backend ""` is rejected by main.py's argparse choices."""
        mod = _load_run_module()
        env = _base_env(tmp_path)
        env["BACKEND"] = ""
        argv = mod.build_argv(env)
        assert argv[argv.index("--backend") + 1] == "torch"

    def test_run_py_has_no_jinja_tokens(self):
        text = RUN_PY.read_text()
        for tok in ("{{", "{%", "{#"):
            assert tok not in text, f"run.py must not contain Jinja token {tok!r}"


class TestCommandShRender:
    def _render(self, config):
        return fill_template(COMMAND_SH.read_text(), {"config": config}, strict=True)

    def test_renders_with_inline_config(self):
        out = self._render({"autotune-config": SAMPLE_AUTOTUNE_CONFIG})
        assert "base64 -d" in out  # materialization branch taken
        assert "AUTOTUNE_CONFIG_FILE" in out
        assert "run.py" in out  # execs the driver

    def test_base64_roundtrip_is_valid_yaml(self):
        out = self._render({"autotune-config": SAMPLE_AUTOTUNE_CONFIG})
        m = re.search(r"echo '([A-Za-z0-9+/=]+)' \| base64 -d", out)
        assert m, "expected an `echo '<b64>' | base64 -d` line"
        decoded = base64.b64decode(m.group(1)).decode()
        assert (
            yaml.safe_load(decoded)["training_config"]["tuning_algorithm"]["default"]
            == "lora"
        )

    def test_fallback_branch_when_no_inline_config(self):
        out = self._render({})  # no autotune-config key
        assert "LLMB_BASH_INPUT_HPO_CONFIG" in out  # fallback path rendered
        assert "base64 -d" not in out  # inline branch not taken

    def test_leads_path_with_python_dir(self):
        out = self._render({"autotune-config": SAMPLE_AUTOTUNE_CONFIG})
        assert "LLMB_BASH_PYTHON_DIR" in out

    def test_command_sh_is_executable(self):
        assert os.access(COMMAND_SH, os.X_OK), "command.sh must be committed with +x"

    def test_installs_real_fm_tune_extra_for_ray(self):
        # fm-tune's `ray` dep (imported unconditionally by main.py) lives in the
        # [core]/[full] extras, NOT the base package, so the venv install must use a
        # real, param-driven extra defaulting to core.
        out = self._render({"autotune-config": SAMPLE_AUTOTUNE_CONFIG})
        assert "FM_TUNE_EXTRA" in out  # extra is param-driven
        assert (
            "${FM_TUNE_ROOT}[${FM_TUNE_EXTRA}]" in out
        )  # extra applied to the editable install

    def test_empty_fm_tune_extra_is_not_overridden_by_the_default(self):
        # `${VAR:-default}` substitutes on empty as well as unset, which would make
        # the documented base-only install (FM_TUNE_EXTRA=) unreachable and the
        # `pip install -e "$FM_TUNE_ROOT"` fallback dead code. `-` is required.
        out = self._render({"autotune-config": SAMPLE_AUTOTUNE_CONFIG})
        assert "${FM_TUNE_EXTRA-core}" in out
        assert "${FM_TUNE_EXTRA:-core}" not in out

    def test_rendered_command_sh_is_valid_bash(self, tmp_path):
        """`bash -n` the rendered script: the string-presence assertions here cannot
        catch a shell syntax error, and this file is executed verbatim at run time.
        """
        for config in ({"autotune-config": SAMPLE_AUTOTUNE_CONFIG}, {}):
            script = tmp_path / "command.sh"
            script.write_text(self._render(config))
            proc = subprocess.run(
                ["bash", "-n", str(script)], capture_output=True, text=True
            )
            assert proc.returncode == 0, proc.stderr

    def test_config_is_materialized_outside_the_artifact_dir(self):
        # $LLMB_BASH_OUTPUT_DIR is published as the `custom` model artifact, so the
        # tuning config must not be written into it.
        out = self._render({"autotune-config": SAMPLE_AUTOTUNE_CONFIG})
        assert 'CONFIG_FILE="$OUT/' not in out
        assert 'CONFIG_DIR="$(dirname "$OUT")' in out

    def test_hpo_config_fileset_may_be_a_directory(self):
        # `hpo_config` is declared type: fileset, so the binding is often a dir;
        # `cp <dir> <file>` would fail under `set -e`.
        out = self._render({})
        assert '-d "$LLMB_BASH_INPUT_HPO_CONFIG"' in out

    def test_setup_command_runs_with_the_step_interpreter_first_on_path(self):
        # The documented `pip install -e .` hook must not resolve to the launcher's
        # or the distro's python.
        out = self._render({"autotune-config": SAMPLE_AUTOTUNE_CONFIG})
        assert 'PATH="$(dirname "$PYTHON"):$PATH"' in out
        assert out.index('dirname "$PYTHON"') < out.index("$SETUP_COMMAND")

    def test_path_is_prepended_not_clobbered(self):
        # On docker LLMB_BASH_PYTHON_DIR is unset and the image's own PATH carries
        # its interpreter; replacing PATH outright would strip conda/venv dirs.
        out = self._render({"autotune-config": SAMPLE_AUTOTUNE_CONFIG})
        assert "${PATH:-" in out

    def test_clone_dir_is_keyed_on_the_ref(self):
        # A single shared clone dir would serve a stale ref to any later build that
        # asked for a different FM_TUNE_REF.
        out = self._render({"autotune-config": SAMPLE_AUTOTUNE_CONFIG})
        assert "fm-tune-src-$FM_TUNE_REF_SLUG" in out
        assert "git fetch" in out  # existing clone is refreshed, not blindly reused

    def test_clones_fm_tune_when_root_is_a_git_url(self):
        # FM_TUNE_ROOT may be a git remote (ssh/https/*.git), not just a local
        # checkout: command.sh detects a URL, clones it once to a local dir, and
        # exports FM_TUNE_ROOT at the clone so the editable install and run.py's
        # cwd both operate on a real tree. FM_TUNE_REF (optional) pins branch/tag.
        out = self._render({"autotune-config": SAMPLE_AUTOTUNE_CONFIG})
        assert "git clone" in out  # clone branch present
        assert "*://*" in out  # URL detection pattern
        assert "FM_TUNE_REF" in out  # optional branch/tag pin
        assert "export FM_TUNE_ROOT=" in out  # repoint to the clone
        # clone must precede the editable install that consumes FM_TUNE_ROOT
        assert out.index("git clone") < out.index("${FM_TUNE_ROOT}[")


class TestBashStepYaml:
    def _load(self):
        return yaml.safe_load((BASH_STEP / "step.yaml").read_text())

    def test_identity_and_artifact_policy(self):
        cfg = self._load()
        assert cfg["name"] == "autotune"
        assert cfg["type"] == "custom"
        assert cfg["config"]["bash"]["skip_finding_output_artifacts"] is True

    def test_io_schema(self):
        cfg = self._load()
        req = cfg["inputs"]["required"]
        assert req["model"]["type"] == "model"
        assert req["dataset_files"]["type"] == "dataset"
        assert cfg["inputs"]["optional"]["hpo_config"]["type"] == "fileset"
        assert cfg["outputs"]["optional"]["custom"]["type"] == "model"

    def test_bash_launcher_and_monitor(self):
        cfg = self._load()
        bash = cfg["environment_configs"]["Bash"]
        assert bash["launchers"]["autotune"]["type"] == "nohup"
        assert bash["launchers"]["autotune"]["monitors"] == ["log_monitor"]
        assert bash["monitors"]["log_monitor"]["ref"] == "space://monitors/bash"

    def test_script_dir_matches_step_name(self):
        assert (BASH_STEP / "bash_scripts/autotune/command.sh").exists()


class TestDockerStep:
    def _load(self):
        return yaml.safe_load((DOCKER_STEP / "step.yaml").read_text())

    def test_scripts_are_byte_identical_to_bash(self):
        for rel in ("bash_scripts/autotune/command.sh", "bash_scripts/autotune/run.py"):
            assert (DOCKER_STEP / rel).read_bytes() == (
                BASH_STEP / rel
            ).read_bytes(), rel

    def test_docker_launcher_and_monitor(self):
        cfg = self._load()
        d = cfg["environment_configs"]["Docker"]
        launcher = d["launchers"]["autotune"]
        assert launcher["type"] == "docker"
        assert "command.sh" in launcher["config"]["command"]
        # No pinned image: Docker._resolve_image prefers launcher_config over
        # config.docker.image, so pinning here would block per-build override.
        assert "image" not in launcher["config"]
        assert d["monitors"]["docker_log"]["ref"] == "space://monitors/docker"

    def test_docker_env_wires_inputs_but_not_tunables(self):
        cfg = self._load()
        env = cfg["environment_configs"]["Docker"]["launchers"]["autotune"]["config"][
            "env"
        ]
        assert "bindings.model.binding.path" in env["LLMB_BASH_INPUT_MODEL"]
        assert (
            "bindings.dataset_files.binding.path"
            in env["LLMB_BASH_INPUT_DATASET_FILES"]
        )
        # Optional input must be wired too -- Docker does not auto-export bindings,
        # so without this the declared hpo_config could never be honored.
        assert "bindings.hpo_config" in env["LLMB_BASH_INPUT_HPO_CONFIG"]
        assert env["BASH_BUILD_VENV"] == "false"
        # Launcher env WINS over config.docker.env, so anything a build should be
        # able to tune must stay out of it.
        assert "BACKEND" not in env
        assert "FM_TUNE_ROOT" not in env

    def test_optional_hpo_config_env_renders_for_every_binding_shape(self):
        """The guard must be total: an optional input that is absent, present-but-
        unbound, or in a context with no `bindings` at all must render to '' rather
        than raising under the step dir's strict=True fill.
        """
        expr = self._load()["environment_configs"]["Docker"]["launchers"]["autotune"][
            "config"
        ]["env"]["LLMB_BASH_INPUT_HPO_CONFIG"]
        cases = [
            ({"bindings": {"model": {"binding": {"path": "/m"}}}}, ""),
            ({"bindings": {"hpo_config": {}}}, ""),
            ({}, ""),
            ({"bindings": {"hpo_config": {"binding": {"path": "/cfg"}}}}, "/cfg"),
        ]
        for data, expected in cases:
            assert fill_template(expr, data, strict=True) == expected, data

    def test_command_sh_copy_is_executable(self):
        assert os.access(DOCKER_STEP / "bash_scripts/autotune/command.sh", os.X_OK)


class TestReferenceBuilds:
    def test_bash_build_shape(self):
        b = yaml.safe_load((SAMPLES / "build.bash.yaml").read_text())["granite.build"]
        target = b["targets"]["custom"]
        assert "bash" in target["environment_uri"]
        step = target["steps"][0]
        assert step["step_uri"] == "space://steps/autotune"
        assert target["inputs"]["model"]["uri"].startswith("hf:")
        assert "dataset_files" in target["inputs"]
        assert "autotune-config" in step["config"]
        env = step["config"]["bash"]["env"]
        assert env["BACKEND"] == "torch"
        assert env["FM_TUNE_EXTRA"] == "core"  # extra that provides ray
        assert "FM_TUNE_ROOT" in env

    def test_docker_build_shape(self):
        b = yaml.safe_load((SAMPLES / "build.docker.yaml").read_text())["granite.build"]
        target = b["targets"]["custom"]
        assert "docker" in target["environment_uri"]
        step = target["steps"][0]
        assert step["step_uri"] == "space://steps/autotune"
        cfg = step["config"]["docker"]
        # The image MUST come from the build: step.yaml pins none (launcher_config
        # would outrank config.docker.image) and there is no env-level default.
        assert cfg["image"]
        # Tunables belong here, not in the launcher env, which would win over them.
        assert cfg["env"]["FM_TUNE_ROOT"]
        assert "BACKEND" in cfg["env"]
        assert "autotune-config" in step["config"]

    def test_docker_sample_keeps_tunables_out_of_the_launcher_env(self):
        """The sample is only meaningful if step.yaml leaves these overridable."""
        launcher_env = yaml.safe_load((DOCKER_STEP / "step.yaml").read_text())[
            "environment_configs"
        ]["Docker"]["launchers"]["autotune"]["config"]["env"]
        sample_env = yaml.safe_load((SAMPLES / "build.docker.yaml").read_text())[
            "granite.build"
        ]["targets"]["custom"]["steps"][0]["config"]["docker"]["env"]
        overridden = sorted(set(sample_env) & set(launcher_env))
        assert not overridden, (
            "launcher env wins over config.docker.env, so these sample values would "
            f"be silently ignored: {overridden}"
        )

    def test_k8s_build_uses_gbstep_and_files_to_create(self):
        b = yaml.safe_load((SAMPLES / "build.k8s.yaml").read_text())["granite.build"]
        step = b["targets"]["custom"]["steps"][0]
        # gbstep is shipped in this repo (src/gbserver/builtins/steps/gbstep) and is
        # what the docs pair with custom_code_config + files_to_create; there is no
        # `custom_code` step asset here.
        assert step["step_uri"] == "space://steps/gbstep"
        ftc = step["config"]["gb"]["files_to_create"]
        # a [{filename: configKey}] entry mapping the tmp path to the autotune-config section
        assert any(v == "autotune-config" for entry in ftc for v in entry.values())
        cfg_path = [
            k for entry in ftc for k, v in entry.items() if v == "autotune-config"
        ][0]
        assert "autotune-config" in step["config"]
        assert cfg_path in step["config"]["custom_code_config"]["start_command"]
        assert (
            "--config_file " + cfg_path
            in step["config"]["custom_code_config"]["start_command"]
        )


class TestStepsSourceTree:
    """The published assets are generated from steps/ -- keep them in lockstep.

    `make check-published` is the authoritative drift check, but it is not wired into
    CI, so these assert the parts that matter cheaply and would catch the most likely
    mistake: hand-editing the generated release under configurations/.
    """

    @pytest.mark.parametrize(
        "src,published",
        [
            (BASH_SRC, BASH_STEP),
            (DOCKER_SRC, DOCKER_STEP),
        ],
        ids=["bash", "docker"],
    )
    def test_source_exists_with_framework_files(self, src, published):
        assert (src / "Makefile").is_file(), f"{src} needs a Makefile"
        assert (src / "step-template.yaml").is_file()
        # USAGE.md is what publish-step ships as the released README.md.
        assert (src / "USAGE.md").is_file()
        assert published.is_dir()

    @pytest.mark.parametrize(
        "src,published",
        [
            (BASH_SRC, BASH_STEP),
            (DOCKER_SRC, DOCKER_STEP),
        ],
        ids=["bash", "docker"],
    )
    def test_published_matches_source(self, src, published):
        """step.yaml, the scripts, and README.md are byte-copies of the source."""
        assert (src / "step-template.yaml").read_bytes() == (
            published / "step.yaml"
        ).read_bytes(), (
            "step.yaml drifted from step-template.yaml; run make publish-step"
        )
        assert (src / "USAGE.md").read_bytes() == (
            published / "README.md"
        ).read_bytes(), "README.md drifted from USAGE.md; run make publish-step"
        for rel in ("bash_scripts/autotune/command.sh", "bash_scripts/autotune/run.py"):
            assert (src / rel).read_bytes() == (
                published / rel
            ).read_bytes(), f"{rel} drifted from source; run make publish-step"

    def test_src_dir_is_pointed_at_bash_scripts(self):
        """The bash/docker launchers require <step>/bash_scripts/<name>/, which
        common.mk's default SRC_DIR=src cannot satisfy. If this override is lost the
        scripts publish to <step>/src/ and the launcher cannot find them.
        """
        for src in (BASH_SRC, DOCKER_SRC):
            assert "SRC_DIR := bash_scripts" in (src / "Makefile").read_text()

    def test_command_sh_stays_jinja_rendered_despite_gbignore(self):
        """The published .gbignore lists `src/**`; because SRC_DIR is bash_scripts it
        must NOT match command.sh, which depends on Jinja to materialize the inline
        config. README.md, by contrast, must be skipped (it shows {{ ... }}).
        """
        from glob import glob

        for published in (BASH_STEP, DOCKER_STEP):
            gbignore = published / ".gbignore"
            assert gbignore.is_file(), f"{published} missing .gbignore"
            ignored = set()
            for line in gbignore.read_text().splitlines():
                line = re.sub(r"#.*", "", line).strip()
                if line:
                    ignored.update(glob(str(published / line), recursive=True))
            assert str(published / "bash_scripts/autotune/command.sh") not in ignored
            assert str(published / "README.md") in ignored
