repos:
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 8.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
