name: sky-lsf
type: Skypilot
config:
  default_cloud: lsf
  idle_minutes_to_autostop: 0
assetstores:
  - store_uri: space://assetstores/env-local
    load:
      - mode: env_local
        config: {}
    push:
      - mode: env_local
        config: {}
