name: docker-test
type: Docker
config:
  defaults:
    pull_policy: "if-not-present"
    env: {}
assetstores:
  - store_uri: space://assetstores/hf/
    load:
      - mode: default
  - store_uri: space://assetstores/local/
    load:
      - mode: default
    push:
      - mode: default
