{{- if and .Values.k8s .Values.k8s.userImagePullSecrets }}
{{- $parentContext := . }}
{{- $jobType := "job" }} # default
{{- if hasKey .Values.run_metadata "job_type" }}
  {{- $jobType = .Values.run_metadata.job_type }}
{{- end }}

{{- $names := list -}}

{{- if eq $jobType "ray" }}
  {{- $names = include "gbraystepbase.imagePullSecretNames" $parentContext | splitList "\n" }}
{{- else }}
  {{- $names = include "gbstepbase.imagePullSecretNames" $parentContext | splitList "\n" }}
{{- end }}

{{- range $idx, $secret := .Values.k8s.userImagePullSecrets }}
{{- $rawName := index $names $idx }}
{{- $finalName := regexReplaceAll "[^a-z0-9-]" (lower $rawName) "-" | trimAll "-" }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $finalName }}
  namespace: {{ $.Release.Namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ $secret.dockerconfigjson | quote }}
---
{{- end }}
{{- end }}