name: slurm-local
type: Skypilot
config:
  default_cloud: slurm
  idle_minutes_to_autostop: 0
  cluster: slurm-docker
  zone: normal
  shared_workdir: /shared
assetstores:
  - store_uri: space://assetstores/hf
    load:
      - mode: hf_pull
        config:
          step_uri: space://steps/hfpull_bash
          cache_path: /shared/hf_cache
    push:
      - mode: hf_push
        config:
          step_uri: space://steps/hfpush_bash
