{{- if .Values.generateResourcesForLLMBBackendCluster }}
{{- if .Values.secrets.enable }}
{{- $mainSecretName := printf "llmbuild-secret-%s" .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ $mainSecretName }}'
  labels:
    'llmbuild/internal': '{{ $mainSecretName }}'
type: Opaque
data:
{{- range $key, $value := .Values.secrets.mainSecret.data }}
  {{ $key | quote }}: {{ $value | quote }}
{{- end }}
{{- range $key, $value := .Values.secrets.mainSecret.stringData }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
