granite.build:
  name: skypilot-slurm-image-hf-test
  targets:
    image-run:
      environment_uri: space://environments/slurm
      inputs:
        input_model:
          uri: hf:///datasets/ibm-research/vira-intents-live
      outputs:
        output_model1:
          uri: hf://huggingface.co/datasets/ibm-research/skypilot-slurm-hf-test1_{{ binding.path | short_hash }}
        output_model2:
          uri: hf://huggingface.co/datasets/ibm-research/skypilot-slurm-hf-test2_{{ binding.path | short_hash }}
      steps:
        - step_uri: space://steps/bash
          config:
            bash_config:
              command: >-
                file=$GB_BUILD_WORKDIR/foo1a.json; touch $file; echo "LLMB_ARTIFACT_ID:output_model1 LLMB_ARTIFACT_PATH:$file";
                file=$GB_BUILD_WORKDIR/foo1b.json; touch $file; echo "LLMB_ARTIFACT_ID:output_model1 LLMB_ARTIFACT_PATH:$file";
                file=$GB_BUILD_WORKDIR/foo2; cp -r {{ bindings.input_model.binding.path }} $file; echo "LLMB_ARTIFACT_ID:output_model2 LLMB_ARTIFACT_PATH:$file"
            compute_config:
              num_gpus_per_node: 0
              total_memory_per_node: 1Gi
