hfpush_config:
k8s:
  image: {{ step_image }}
  env:
    HOME:
      value: "/app"
    HF_TOKEN:
      valueFrom:
        secretKeyRef:
          name: {{ setup_config.space.secret }}
          key: {{ config.hfpush_config.token_secretname | default("HF_TOKEN") }}
